#!/bin/bash

export PYTHONNOUSERSITE=1
unset PYTHONHOME
unset PYTHONPATH

REALPATH=$(dirname "$(readlink -f "$0")")
test -z ${REALPATH} && echo "REALPATH could not be deduced" && exit 1
export PATH="${REALPATH}/bin/:${PATH}"

squigualiser "$@"
exit_code=$?
exit "$exit_code"



