name: Dev_Package_Build

on:
  push:
    branches: [ '**' ]
    tags:
      - '*'  # Run on any new tag
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-package-x86_64-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: make build_dir dir
        run: |
          mkdir -p build_dir && \
          cp test/package/package.sh build_dir/ && \
          chmod +x build_dir/package.sh
      - name: Run package.sh inside Ubuntu 14.04 Docker
        run: |
          docker run --rm -v ${{ github.workspace }}/build_dir:/host/ ubuntu:14.04 /bin/bash -c "
            apt-get update && \
            apt-get install -y git && \
            /host/package.sh docker test_pypi
          "
      - name: decompress squigualiser tar.gz
        run: |
          if [ -f build_dir/squigualiser-*.tar.gz ]; then
            cp build_dir/squigualiser-*.tar.gz .
            echo "Decompressing squigualiser tar.gz"
            tar -xzf squigualiser-*.tar.gz
          else
            echo "No squigualiser tar.gz found!"
            exit 1
          fi
      - name: Get artifact filename
        id: artifact_name
        run: |
          FILE=$(ls build_dir/squigualiser-*.tar.gz)
          BASENAME=$(basename "$FILE" .tar.gz)
          echo "ARTIFACT_NAME=$BASENAME" >> $GITHUB_ENV
          LATEST_TAG=$(git ls-remote --tags ${REPO_LINK} | cut -d/ -f3 | grep -v '\^{}' | sort -V | tail -n1)
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
      - name: quick run
        run: |
          ./squigualiser-${{ env.LATEST_TAG }}/squigualiser --help || exit 1
          ./squigualiser-${{ env.LATEST_TAG }}/squigualiser --version || exit 1
      - name: Add squigualiser to PATH
        run: echo "${{ github.workspace }}/squigualiser-${{ env.LATEST_TAG }}" >> $GITHUB_PATH
      - name: test_reform
        run: test/test_reform.sh
      - name: test_realign
        run: test/test_realign.sh
      - name: test_signal_to_read_plot
        run: test/test_plot_signal_to_read.sh --save_svg
      - name: test_calculate_offsets
        run: test/test_calculate_offsets.sh
      - name: Upload squigualiser tar.gz
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: build_dir/squigualiser-*.tar.gz
  build-package-x86_64-macos:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: make build_dir dir
        run: |
          mkdir -p build_dir && \
          cp test/package/package.sh build_dir/ && \
          chmod +x build_dir/package.sh
      - name: run without docker
        run: |
          cd build_dir && \
          ./package.sh nodocker test_pypi && \
          cd ..
      - name: decompress squigualiser tar.gz
        run: |
          if [ -f build_dir/squigualiser-*.tar.gz ]; then
            cp build_dir/squigualiser-*.tar.gz .
            echo "Decompressing squigualiser tar.gz"
            tar -xzf squigualiser-*.tar.gz
          else
            echo "No squigualiser tar.gz found!"
            exit 1
          fi
      - name: Get artifact filename
        id: artifact_name
        run: |
          FILE=$(ls build_dir/squigualiser-*.tar.gz)
          BASENAME=$(basename "$FILE" .tar.gz)
          echo "ARTIFACT_NAME=$BASENAME" >> $GITHUB_ENV
          LATEST_TAG=$(git ls-remote --tags ${REPO_LINK} | cut -d/ -f3 | grep -v '\^{}' | sort -V | tail -n1)
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
      - name: quick run
        run: |
          ./squigualiser-${{ env.LATEST_TAG }}/squigualiser --help || exit 1
          ./squigualiser-${{ env.LATEST_TAG }}/squigualiser --version || exit 1
      - name: Add squigualiser to PATH
        run: echo "${{ github.workspace }}/squigualiser-${{ env.LATEST_TAG }}" >> $GITHUB_PATH
      - name: test_reform
        run: test/test_reform.sh
      - name: test_realign
        run: test/test_realign.sh
      - name: test_signal_to_read_plot
        run: test/test_plot_signal_to_read.sh --save_svg
      - name: test_calculate_offsets
        run: test/test_calculate_offsets.sh
      - name: Upload squigualiser tar.gz
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: build_dir/squigualiser-*.tar.gz
  build-package-arm64-macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: make build_dir dir
        run: |
          mkdir -p build_dir && \
          cp test/package/package.sh build_dir/ && \
          chmod +x build_dir/package.sh
      - name: run without docker
        run: |
          cd build_dir && \
          ./package.sh nodocker test_pypi && \
          cd ..
      - name: decompress squigualiser tar.gz
        run: |
          if [ -f build_dir/squigualiser-*.tar.gz ]; then
            cp build_dir/squigualiser-*.tar.gz .
            echo "Decompressing squigualiser tar.gz"
            tar -xzf squigualiser-*.tar.gz
          else
            echo "No squigualiser tar.gz found!"
            exit 1
          fi
      - name: Get artifact filename
        id: artifact_name
        run: |
          FILE=$(ls build_dir/squigualiser-*.tar.gz)
          BASENAME=$(basename "$FILE" .tar.gz)
          echo "ARTIFACT_NAME=$BASENAME" >> $GITHUB_ENV
          LATEST_TAG=$(git ls-remote --tags ${REPO_LINK} | cut -d/ -f3 | grep -v '\^{}' | sort -V | tail -n1)
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
      - name: quick run
        run: |
          ./squigualiser-${{ env.LATEST_TAG }}/squigualiser --help || exit 1
          ./squigualiser-${{ env.LATEST_TAG }}/squigualiser --version || exit 1
      - name: Add squigualiser to PATH
        run: echo "${{ github.workspace }}/squigualiser-${{ env.LATEST_TAG }}" >> $GITHUB_PATH
      - name: test_reform
        run: test/test_reform.sh
      - name: test_realign
        run: test/test_realign.sh
      - name: test_signal_to_read_plot
        run: test/test_plot_signal_to_read.sh --save_svg
      - name: test_calculate_offsets
        run: test/test_calculate_offsets.sh
      - name: Upload squigualiser tar.gz
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: build_dir/squigualiser-*.tar.gz


